### ISSUE TITLE
Can't find data files for tutorial?

### ISSUE THREAD

**Issue by j-a-t** [EmSherratt/geomorph#6]
Hi Emma,

A friend of mine recently suggested I check out geomorph to analyse some morphometric data I'm collecting for my thesis. I've never done morphometrics before so was working thorugh the user manual.

However, I can't find the datafiles, e.g. .tps or .nts extensions.

    > mydata <- readland.tps("ratland.tps", specID = "ID")
    Error in file(file, "r") : cannot open the connection
    In addition: Warning message:
    In file(file, "r") :
      cannot open file 'ratland.tps': No such file or directory

It's a working directory issue so I was trying to find where they were so I could put them in my WD. When I tried searching for them (specifically by name, e.g. "ratlands.tps") on my computer I couldn't find them. 

I'm on a Windows using RStudio, installed the packaged and used library(geomorph) to open the package. Have I missed something? Otherwise would you be able to make all the files for the tutorial available?

Thanks heaps, and regards.

~ Josh (j-a-t)

**Comment by EmSherratt** [comment]
Hi,

Yes you are misunderstanding the user manual. That code is showing you how
you would input a file of those kinds, as exemplified by the "screenshot"
example of the file in a square. There are no files for you to read in. I
suggest running the examples that use the example datasets saved within
geomorph.

Emma

On Sunday, 11 October 2015, j-a-t <notifications@github.com> wrote:

> Hi Emma,
>
> A friend of mine recently suggested I check out geomorph to analyse some
> morphometric data I'm collecting for my thesis. I've never done
> morphometrics before so was working thorugh the user manual.
>
> However, I can't find the datafiles, e.g. .tps or .nts extensions.
>
> > mydata <- readland.tps("ratland.tps", specID = "ID")
> Error in file(file, "r") : cannot open the connection
> In addition: Warning message:
> In file(file, "r") :
>   cannot open file 'ratland.tps': No such file or directory
>
> It's a working directory issue so I was trying to find where they were so
> I could put them in my WD. When I tried searching for them (specifically by
> name, e.g. "ratlands.tps") on my computer I couldn't find them.
>
> I'm on a Windows using RStudio, installed the packaged and used
> library(geomorph) to open the package. Have I missed something? Otherwise
> would you be able to make all the files for the tutorial available?
>
> Thanks heaps, and regards.
>
> ~ Josh (j-a-t)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmSherratt/geomorph/issues/6>.
>


-- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Emma Sherratt, PhD.

Lecturer in Zoology,
Zoology Division, School of Environmental and Rural Science,
Room L112 Bldg C02,
University of New England,
Armidale, NSW, Australia, 2351
Tel: +61 2 6773 5041
email: emma.sherratt@une.edu.au
Twitter: @DrEmSherratt

Caecilians are legless amphibians...

*                      __
    (\   .-.   .-.   /_")
     \\_//^\\_//^\\_//
      `"`   `"`   `"`*

learn more about them here: www.emmasherratt.com/caecilians

**Comment by j-a-t** [comment]
Thanks Emma.
